name: MurderMysteryy
version: 1.0
author: ItsToxicGG
main: murdermystery\
api: 4.0.0

commands:
  murdermystery:
    description: Murder Mystery Command
    usage: "/murdermystery"
    permission: murdermystery.command
